export const FETCH_PHONES_SUCCESS = 'FETCH_PHONES_SUCCESS'

export const FETCH_PHONE_BY_ID_SUCCESS = 'FETCH_PHONE_BY_ID_SUCCESS'

export const ADD_PHONE_TO_BASKET = 'ADD_PHONE_TO_BASKET'
export const REMOVE_PHONE_FROM_BASKET = 'REMOVE_PHONE_FROM_BASKET'
export const CLEAN_BASKET = 'CLEAN_BASKET'
